services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    environment:
      DELETE_FILE_ON_TRASHCAN: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metube.rule=Host(`metube.${MAIN_DOMAIN}`)"
      - "traefik.http.routers.metube.entrypoints=websecure"
      - "traefik.http.routers.metube.tls.certresolver=mydnschallenge"
      - "traefik.http.services.metube.loadbalancer.server.port=8081"
    volumes:
      - /path/to/downloads:/downloads
