services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    restart: unless-stopped
    env_file: ../../.env
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stirling-pdf.rule=Host(`stirling-pdf.${MAIN_DOMAIN}`)"
      - "traefik.http.routers.stirling-pdf.entrypoints=websecure"
      - "traefik.http.routers.stirling-pdf.tls.certresolver=mydnschallenge"
      - "traefik.http.services.stirling-pdf.loadbalancer.server.port=8080"
    volumes:
      - ./stirling-data:/configs
    networks:
      - proxy-tier
networks:
  proxy-tier:
    external: true
