services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: homelab-server
    restart: unless-stopped
    env_file: ../../.env
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ACCEPT_DNS=false
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./tailscale-data:/var/lib/tailscale
    cap_add:
      - net_admin
      - sys_module
    networks:
      - proxy-tier
networks:
  proxy-tier:
    external: true
