include:
  - path: ./tailscale/docker-compose.yaml
  - path: ./proxy/docker-compose.yaml
  - path: ./homepage/docker-compose.yaml
  - path: ./coredns/docker-compose.yaml
  - path: ./stirling-pdf/docker-compose.yaml

services: {}
