services:
  traefik:
    image: traefik:v3.6.8
    container_name: traefik
    depends_on: [tailscale]
    network_mode: "service:tailscale" # Traefik "lives" inside Tailscale
    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      # DNS Challenge (Let's Encrypt)
      - "--certificatesresolvers.mydnschallenge.acme.dnschallenge=true"
      - "--certificatesresolvers.mydnschallenge.acme.dnschallenge.provider=route53"
      - "--certificatesresolvers.mydnschallenge.acme.email=${ADMIN_EMAIL}"
      - "--certificatesresolvers.mydnschallenge.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${MAIN_DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=mydnschallenge"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy-tier"
    environment:
      - "AWS_REGION=${AWS_REGION}"
      - "AWS_HOSTED_ZONE_ID=${AWS_HOSTED_ZONE_ID}"
      - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
      - ./letsencrypt:/letsencrypt

  whoami:
    image: traefik/whoami
    container_name: traefik-whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${MAIN_DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=mydnschallenge"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
    networks:
      - proxy-tier
networks:
  proxy-tier:
    external: true
