services:
  coredns:
    image: coredns/coredns:latest
    container_name: coredns
    restart: unless-stopped
    command: -conf /etc/coredns/Corefile
    depends_on: [tailscale]
    network_mode: "service:tailscale"
    labels:
      - "komodo.skip=true"
    volumes:
      - ./Corefile:/etc/coredns/Corefile:ro
