---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/pfabriziof
          icon: github.svg
    - Gists:
        - href: https://gist.github.com/pfabriziof
          icon: github.svg

- Social:
    - X:
        - abbr: X
          href: https://x.com/
          icon: x.svg
    - Pinterest:
        - abbr: PI
          href: https://www.pinterest.com/
          icon: pinterest.svg
    - Reddit:
        - abbr: RE
          href: https://reddit.com/
          icon: reddit.svg

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
          icon: youtube.svg
    - YouTube:
        - abbr: YT-M
          href: https://music.youtube.com/
          icon: youtube-music.svg
