---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/pfabriziof
          icon: github.svg
    - Gists:
        - href: https://gist.github.com/pfabriziof
          icon: github.svg

- Social:
    - Reddit:
        - abbr: RE
          href: https://reddit.com/
          icon: reddit.svg

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
          icon: youtube.svg
