---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks
# For exploring the available icons, please see:
# https://dashboardicons.com

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/pfabriziof
          icon: github.svg
    - Gists:
        - href: https://gist.github.com/pfabriziof
          icon: github.svg

- Social:
    - X:
        - abbr: X
          href: https://x.com/
          icon: x.svg
    - Pinterest:
        - abbr: PI
          href: https://www.pinterest.com/
          icon: pinterest.svg
    - Reddit:
        - abbr: RE
          href: https://reddit.com/
          icon: reddit.svg

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
          icon: youtube.svg
    - YouTube:
        - abbr: YT-M
          href: https://music.youtube.com/
          icon: youtube-music.svg
- Books:
  - LibGen.li:
    - abbr: LG
      href: https://libgen.li
      icon: bookstack.svg
  - LibGen.la:
    - abbr: LG
      href: https://libgen.la
      icon: bookstack.svg
  - LibGen.bz:
    - abbr: LG
      href: https://libgen.bz
      icon: bookstack.svg
  - LibGen.gl:
    - abbr: LG
      href: https://libgen.gl
      icon: bookstack.svg
