- Admin:
    - Tailscale:
        icon: tailscale.svg
        href: https://login.tailscale.com/admin/machines
    - Traefik:
        icon: traefik-proxy.svg
        href: https://traefik.thepots.net/
    - Komodo:
        icon: komodo.svg
        href: https://komodo.thepots.net/
    - Dozzle:
        icon: dozzle.svg
        href: https://localhost/
    - Pi-hole:
        icon: pi-hole.svg
        href: http://localhost/
- Utilities:
    - Immich:
        icon: immich.svg
        href: http://localhost/
    - File Browser:
        icon: filebrowser.svg
        href: http://localhost/
    - Stirling-PDF:
        icon: stirling-pdf.svg
        href: https://stirling-pdf.thepots.net/
    - IT-Tools:
        icon: it-tools.svg
        href: https://it-tools.thepots.net/
    - Linkding:
        icon: linkding.svg
        href: http://localhost/
- Media:
    - Navidrome:
        icon: navidrome.svg
        href: http://localhost/
    - Jellyfin:
        icon: jellyfin.svg
        href: http://localhost/
    - Calibre:
        icon: calibre.svg
        href: http://localhost/
    - Calibre-Web:
        icon: calibre-web.svg
        href: http://localhost/
- Download Media:
    - Prowlarr:
        icon: prowlarr.svg
        href: http://localhost/
    - Lidarr:
        icon: lidarr.svg
        href: http://localhost/
    - Radarr:
        icon: radarr.svg
        href: http://localhost/
    - Sonarr:
        icon: sonarr.svg
        href: http://localhost/
    - MeTube:
        icon: metube.svg
        href: http://localhost/
